### ISSUE TITLE
[Docker-Desktop-Extension] Bump security dependencies

### ISSUE THREAD

**Issue by mmartin24** [epinio/extension-docker-desktop#23]
### Issue:
Bump the listed dependencies for docker desktop extensions listed here: https://github.com/epinio/extension-docker-desktop/security/dependabot . 

Summary of list here:

- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/10
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/19 
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/18
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/15
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/14
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/13
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/12
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/11
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/1
- [ ] https://github.com/epinio/extension-docker-desktop/security/dependabot/16

**Comment by andreas-kupries** [comment]
The consolidated requested version bumps are

- "decode-uri-component": ">=0.2.1"
- "json5": ">=2.2.2"
- "loader-utils": ">=3.2.1"
- "minimatch": ">=3.0.5"
- "nth-check": ">=2.0.1"

Checking the `package(-lock).json` none of these are direct dependencies.
All of them look to be indirect dependencies.

**Comment by andreas-kupries** [comment]
Trawling the docs ... Had to `zypper install npm18` (version 9.6.5) to match the lock version (v2) ...
Trying to `npm i --package-lock-only` with unchanged package.json ... reports that there are issues.
And the referenced `npm audit` tells me the same things we got from the dependabot.

The really nice fix is the reference to `npm audit fix` to apply the necessary fixes/bumps.
